# ICAOD 1.0.0 
* The vignette is updated.
* The class bayes is removed and replaced by class minimax
* Dr. Seongho Kim joined us as an author

# ICAOD 0.9.9 
* a vignette is added.
* The crt_method and sens_method arguments in bayes are now placed in crt.bayes.control and sens.bayes.control with a new name method.
* Adding a new argument in all optimal design functions: sens.control

# ICAOD 0.9.8
* Gaussian Quadrature formulas are added from package mvQuad.
* A bug in CPU time is fixed.
* Help pages are improved.
* spell checking passed

# ICAOD 0.9.7
* A bug is fixed in minimax designs.
* Adding efficiency functions beff and leff.


# ICAOD 0.9.6
* Still beta version
* A formula interface is added
* A prominent change since this version
* Please use only the last version

# ICAOD 0.9.2
* ##### fixing Bug1: exporting the S3 iterate method
* improving the documentation.
* changing the name of "equivalence_on_average"" to "equivalence_ave"
* changing the name of "on_average_ICA" to "ave"
* adding a documentation for the ICAOD package in "ICAOD.R"
* check the spelling by devtools
* 


# ICAOD 0.9.1

* The first release of the ICAOD package.
* ##### Bug1: "iterate" was not exported.
* some typos in the documentation
+ I am not happy with the name of the functions "equivalence_on_average" and "on_average_ICA"
